### ISSUE TITLE
[Enhancement - Dashboard] Center the text in the Dashboard tiles

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1016]
# 🙋 feature request

1. Center the values in the Dashboard Tiles
2. Fix legend in the Compliance Trend

## 🤔 Expected Behavior

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/31665420/228577350-ac38cdc6-ff5b-4adf-8676-f82b57e732a4.png">

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/31665420/228587567-23d88df7-c91d-4594-968a-95a51f568b44.png">

## 😯 Current Behavior

<img width="893" alt="image" src="https://user-images.githubusercontent.com/31665420/228577668-48b18670-53ff-41ff-88f3-b5f5afd28b7a.png">

**Comment by astra1** [comment]
I will work on this feature
