### ISSUE TITLE
[Enhancement - Policy] Update the look and feel of the policy screen

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1017]
# 🙋 feature request

## 🤔 Expected Behavior

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/31665420/228580216-3bffcdda-195b-4714-bf9e-b8a059c3742d.png">

**Comment by astra1** [comment]
will make this enhancement

**Comment by plyubich** [comment]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/31665420/228648697-f240dc0f-2e5f-4123-8f6b-961f3815c49b.png">

**Comment by plyubich** [comment]
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/31665420/228649270-6b8eb442-2cdb-41d3-b72b-2381472636a6.png">

**Comment by plyubich** [comment]
@astra1 
1. can you please see if you can add the icons as in the dashboard for each category
<img width="203" alt="image" src="https://user-images.githubusercontent.com/31665420/229146772-e1f50f43-7bd0-4463-836e-4101be7b0d77.png">
2. can you try to add the number in the category inline and just make the whole tile clickable
<img width="791" alt="image" src="https://user-images.githubusercontent.com/31665420/229147902-f7d1f387-1c5d-4950-8b6c-86d5da19c72e.png">
