### ISSUE TITLE
[Enhancement - Policy Details] Update look and feel of the policy details screen

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1018]
# 🙋 feature request

<img width="1795" alt="image" src="https://user-images.githubusercontent.com/31665420/228583375-492814f0-8df5-4341-abe3-1746e1406954.png">

1. Fix the Policy title - should be friendly name
2. Move the information in the tiles into the Policy Details page, however, we just need to display the data, hence tiles are no longer necessary
3. Remove items marked with red X - this information we will not expose to the user

**Comment by astra1** [comment]
I'll pick up the enhancement

**Comment by plyubich** [comment]
@astra1 can you see about these items please.
![image](https://user-images.githubusercontent.com/31665420/228906799-19a85905-36dc-4c9d-bf4a-5ec8c2efcefa.png)

**Comment by plyubich** [comment]
@astra1 

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/31665420/229194765-c34670e8-8752-48ae-87ec-3b31a1559a0f.png">
