### ISSUE TITLE
Issue while Adding AWS Account [BUG]

### ISSUE THREAD

**Issue by shoebshaikh1** [PaladinCloud/CE#1021]
(This is in reference to issue #980)
Hi @rnithinpaladin, I was trying to add the AWS account to Paladin and I am facing some issues as I had to run the upgrade command which redeployed the entire stack probably. I made the same changes in the task definitions that we had made earlier, however, I am still getting the same error and am unable to log in. Can we quickly connect and check the configurations once? Thanks!

**Comment by rnithinpaladin** [comment]
https://meet.google.com/ojm-yfkz-wgo?authuser=0

**Comment by Subbu-PaladinCloud** [comment]
Hi @shoebshaikh1 , please join our slack ( https://paladincloud.io/ and click on slack link ), we can have much easier convo.

**Comment by Subbu-PaladinCloud** [comment]
Please let us know when you are ready to join, we can jump on a call with you

**Comment by Subbu-PaladinCloud** [comment]
Hi @shoebshaikh1 , let us use https://meet.google.com/ojm-yfkz-wgo?authuser=0 to get on a call

**Comment by shoebshaikh1** [comment]
@Subbu-PaladinCloud , Yes I am connecting on the above link.

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
