### ISSUE TITLE
[BUG - Dashboard] After selecting the custom date in the asset graph, the next clean clears the menu

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1022]
## Reproduce steps

1. Go to the Dashboard
2. Click "All Time" dropdown -> custom -> pick date -> apply
3. Click "All Time" dropdown - the menu will be empty

<img width="873" alt="image" src="https://user-images.githubusercontent.com/31665420/228857586-16fd94b2-84c7-4a11-b583-efc067ca550e.png">

## Expected Results

Menu should not be empty

## Actual Results

menu is empty

**Comment by astra1** [comment]
looking into this
