### ISSUE TITLE
[Enhancement - Notifications] Create the Notifications List View Screen

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1036]
# 🙋 feature request
This feature will be a replacement for the Fix Central Screen. It will contain both Paladin Cloud notification + external sources

<img width="641" alt="image" src="https://user-images.githubusercontent.com/31665420/229226032-e9762c24-0f41-4f86-9c0d-c846090c7b9c.png">

**Comment by astra1** [comment]
working on this

**Comment by plyubich** [comment]
This screen was created internally
