### ISSUE TITLE
enhancement request: Add a view to see Paladin Cloud notifications

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

When clicking on any Paladin Cloud notifications, create a view to display the contents of this notification

### Anything else?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/31665420/229239199-359bc31e-6930-4db5-8575-13146cc66c42.png">

**Comment by astra1** [comment]
working on this

**Comment by plyubich** [comment]
completed by internal team
