### ISSUE TITLE
No Data issues in Asset Groups

### ISSUE THREAD

**Issue by kkhamruddin-pk** [PaladinCloud/CE#1051]
For few of the fields we see there is no data available in asset group.

Could you please help

![image](https://user-images.githubusercontent.com/33874243/229891657-bfb83d90-385a-4acc-9a08-9ac90cb32056.png)

**Comment by PaladinCloudJohn** [comment]
Oh no. @kkhamruddin-pk, thanks for letting us know. I've flagged this to the engineering team to investigate. We'll let you know what they find.

**Comment by Subbu-PaladinCloud** [comment]
Hi @kkhamruddin-pk , could you please check the JSON file in S3 under PaladinCloud Data/inventory and within Resourcegroup to see if there was data being retrieved from this account in Azure ?

**Comment by Subbu-PaladinCloud** [comment]
Something of this sort

![image](https://user-images.githubusercontent.com/112977703/229915460-54522b2f-4dbd-4fed-ab0d-63992b308b9a.png)

**Comment by Subbu-PaladinCloud** [comment]
Also, further checking on this on our side.. it doesnt look like we are getting this data either.. let me talk internally to see if these fields are valid for Azure on the report.

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
