### ISSUE TITLE
enhancement request: Update the Assets -> List view to mimic the style of Violations page

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

<img width="1797" alt="image" src="https://user-images.githubusercontent.com/31665420/230159896-e16cb77a-4c2a-4cff-9fcb-c36c1a648367.png">

### 🧑‍💻 Implementation

Follow the new style of the violations list for the Asset -> List page

**Comment by astra1** [comment]
I'll follow up
