### ISSUE TITLE
enhancement request: Asset Distribution page enhancements

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Use the below guidelines for Asset Distribution page enhancements

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/31665420/231267343-740fc8d7-9bac-4bfd-a464-79e64345f6ec.png">

**Comment by astra1** [comment]
I will make this enhancement

**Comment by plyubich** [comment]
@astra1 Also, can we add a hand mouse cursor when mouseover the tile
