### ISSUE TITLE
enhancement request: <Header of List view>

### ISSUE THREAD

**Issue by lakspp** [PaladinCloud/CE#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Change the header sort icons from the current view to as attached. The arrow should show on default sorted column and other columns to show arrow on hover. 
![Screenshot 2023-04-19 204401](https://user-images.githubusercontent.com/103980847/233121469-b4ab7d99-0e69-47cc-8bae-8decdd325caf.jpg)

**Comment by astra1** [comment]
I can try to fix it
