### ISSUE TITLE
enhancement request: Numbers across the UI to match the browser selection

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Numbers across the UI to match the browser selection

### 🧑‍💻 Implementation

Use Pipe
Need the following screens in priority:
1. Dashboard
2. Asset Group Selector
3. Asset - Summary
4. Asset - Distribution
5. Violations
6. Global - Table - Result

**Comment by astra1** [comment]
I'll make it

**Comment by plyubich** [comment]
@astra1 I believe there is a missed numbers pipe on the asset group selector
<img width="260" alt="image" src="https://user-images.githubusercontent.com/31665420/234016048-1822a903-30f1-4afa-a8ee-682241965162.png">
