### ISSUE TITLE
[BUG] Login page stuck at "Please wait, while we fetch your access roles..."

### ISSUE THREAD

**Issue by tejapv** [PaladinCloud/CE#1184]
## Microservices
- Spring boot Applications:

 - Admin Service
 - Auth Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:

 - 1.8

 

## Summary
After installing the tool, login page is stuck with "Please wait, while we fetch your access roles..." message. I can see below error message in developer console.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/12740334/235803267-a0ad9e2b-9ef9-4e45-99a3-c1ac94bf75da.png">

It looks like the issue is something to do with SSL certificate. I followed the steps exactly as mentioned in this page for SSL certificate creation

https://github.com/PaladinCloud/CE/wiki/Deploy-Paladin

## Reproduce steps
Follow the exact steps listed in the wiki page. 

MAKE_ALB_INTERNAL = True
ALB_PROTOCOL = "HTTPS"
SSL_CERTIFICATE_ARN = "validawsarn"  # Required only if ALB_PROTOCOL is defined as HTTPS
PALADINCLOUD_DOMAIN = "beta.example.io"  # Required only if you point a CNAME record to ALB ex: app.paladincloud.com

## Expected Results

I should be able to login.

## Actual Results

Not able to login. Login page is stuck at "Please wait, while we fetch your access roles"

**Comment by Subbu-PaladinCloud** [comment]
Hi @tejapv , could you check your Auth Services under ECS cluster ( Paladincloud ) and see if that is active ? Also, please join our slack channel for quicker response/feedback. ( www.paladincloud.io and click on Slack)

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
