### ISSUE TITLE
[BUG] yourdomian.com/pl shows empty page instead of sending to dashboard

### ISSUE THREAD

**Issue by mkinchin-paladin** [PaladinCloud/CE#1226]
## Microservices
- Spring boot Applications:

## Webapp
 
- OS Type: Windows
- Java version:
 - 1.8

## Summary
Please see pic below.
![image](https://github.com/PaladinCloud/CE/assets/133698330/9a1775ca-7fba-46ef-bc54-1134a50b13ef)
When type "/pl" or "/pl/" it opens empty page with no date

## Reproduce steps
Just go to "where_paladin_is_deployed/pl"

## Expected Results
Be redirected to dashboard as it goes with every other not existing URL

## Actual Results
Show regular UI but with NO data at all

**Comment by astra1** [comment]
@mkinchin-paladin fixed via #1254
