### ISSUE TITLE
Click on main logo leads to the dashboard

### ISSUE THREAD

**Issue by mkinchin-paladin** [PaladinCloud/CE#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

I've used a lot of different services and I became used to some things you expect out of interface. One of them that main logo do something. And in particular, it leads you to the main page of the application. So in case in Paladin Cloud it would be nice to have a link to the dashboard there.
![image](https://github.com/PaladinCloud/CE/assets/133698330/047bc2d3-4efc-455b-bd15-a7fd7c85cb18)

**Comment by astra1** [comment]
@mkinchin-paladin implemented via #1253
