### ISSUE TITLE
enhancement request: Implement the new filter design in the list view components

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Enhance the filters approach in the tables of Paladincloud to significantly improve usability and efficiency for users. The revamped filters will provide users with a more intuitive and powerful filtering experience, allowing them to easily navigate and analyse data within the tables. By implementing these enhancements, we aim to enhance user productivity, streamline data exploration, and optimise the overall user experience in Paladincloud.

https://www.loom.com/share/525bc85e3b48476b81837741ec5dfef1

### Anything else?

Use in the commit msg -> UIUX-3

Here are the designs for the filters
[Filters-happy-flow.pdf](https://github.com/PaladinCloud/CE/files/11553634/Filters-happy-flow.pdf)
[Filters-Edge-cases.pdf](https://github.com/PaladinCloud/CE/files/11553635/Filters-Edge-cases.pdf)

**Comment by plyubich** [comment]
@astra1 please take a look at this issue

**Comment by astra1** [comment]
working on it
