### ISSUE TITLE
enhancement request: Tutorials under User Settings need to be updated

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#1274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Please get the screens updated to the latest look and feel and navigation.

### 🧑‍💻 Implementation

jira commit - CUS-53

**Comment by rammvenk** [comment]
@astra1 Can you please look into this?

**Comment by astra1** [comment]
@rammvenk fixed via #1284
