### ISSUE TITLE
Error: creating Cognito User Pool: AccessDeniedException:

### ISSUE THREAD

**Issue by lferrari-navis** [PaladinCloud/CE#1576]
I tried to follow the PaladinCloud installation procedure but during Terraform implementation it stopps at resource 122 or 133 or 136 our of 1099. The error I'm getting though is consistent:

Error occured, please check error log for more details
Error Message:  Error occured, please check error log for more details

Creating Cognito User Pool: AccessDeniedException: User: arn:aws:sts::795375171603:assumed-role/PaladinCloudInstallerRole/i-0197c32fe3aadff35 is not authorized to perform: cognito-idp:CreateUserPool on resource: arn:aws:cognito-idp:us-east-1:795375171603:userpool/* because no identity-based policy allows the cognito-idp:CreateUserPool action
        status code: 400, request id: 8bfb673e-a303-45fc-8eec-a4200fe5f403

Can you help me understand how this can be fixed?

Thanks,
Luciano Ferrari

**Comment by lferrari-navis** [comment]
updated title of the bug

**Comment by Subbu-PaladinCloud** [comment]
@lferrari-navis , you seem to have closed the bug, is the error resolved ? could you paste your local.py screen shot here to see what was put in the cognito domain name ?

**Comment by lferrari-navis** [comment]
I had to manually give the PaladinInstallerRole Cognito access and redeploy it. Now Its only doing around 200 remaining deployments

**Comment by lferrari-navis** [comment]
Now it's like this Resources created: 55/268, Time elapsed: 14m 18s [... ]   but taking 14 minutes already.... lets see

**Comment by Subbu-PaladinCloud** [comment]
ok.. deployment takes about 20 -30 min

**Comment by lferrari-navis** [comment]
> @lferrari-navis , you seem to have closed the bug, is the error resolved ? could you paste your local.py screen shot here to see what was put in the cognito domain name ?

I used kalerispaladin I think

**Comment by lferrari-navis** [comment]
> Now it's like this Resources created: 55/268, Time elapsed: 14m 18s [... ] but taking 14 minutes already.... lets see

ok, it's moving now: 69/268, Time elapsed: 17m 31s

**Comment by lferrari-navis** [comment]
> ok.. deployment takes about 20 -30 min

Installation is completed and I received an email with url but getting error: The connection has timed out

The server at internal-kaleris-paladin-1760488746.us-east-1.elb.amazonaws.com is taking too long to respond.

**Comment by Subbu-PaladinCloud** [comment]
how are you accessing this ? Please follow the steps for Portal access https://paladincloud.io/docs/connect-to-the-portal-after-installation/

**Comment by Subbu-PaladinCloud** [comment]
Hi @lferrari-navis , are you able to access the portal ? Please let us know if any issues.
