### ISSUE TITLE
Installation failing on 3.0.0

### ISSUE THREAD

**Issue by apoorv-byjus** [PaladinCloud/CE#1752]
Error Message: 
Error: local-exec provisioner error

  with null_resource.pacbot_app_build_ui_and_api_BuildUiAndApis,
  on pacbot_app_build_ui_and_api_BuildUiAndApis.tf.json line 37, in resource.null_resource.pacbot_app_build_ui_and_api_BuildUiAndApis.provisioner[0].local-exec:
  37:                         }

Error running command
'/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py':
exit status 1. Output: Uploading Email templates to S3...............

Email templates upload to S3 completed!!!

Maven build started...

Started building the jar...............

Traceback (most recent call last):
  File "/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 308, in <module>
    Buildpacbot(
  File "/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 57, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code(bucket, s3_key_prefix)
  File "/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 130, in build_jar_and_ui_from_code
    self.build_api_job_jars(self.codebase_root_dir)
  File "/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 141, in build_api_job_jars
    stdout, stderr = self.run_bash_command(self.mvn_build_command, working_dir)
  File "/home/ec2-user/CE/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 113, in run_bash_command
    raise Exception("Error: PacBot maven build failed. Please check log, %s " % str(self.maven_build_log))
Exception: Error: PacBot maven build failed. Please check log,
/home/ec2-user/CE/installer/log/maven_build.log

**Comment by rnithinpaladin** [comment]
Hi @apoorv-byjus,

Thank you for trying paladincloud. I apologize for the interruption, but we need to debug your issue. Please share the following information with us:
share CE/installer/log/maven_build.log file with us.

This information will help us to diagnose the problem and resolve it as quickly as possible.

Thanks,
Nithin.R

**Comment by apoorv-byjus** [comment]
Hi Nithin,

Please find attached the requested log.

Regards,
Apoorv

[maven_build.log](https://github.com/PaladinCloud/CE/files/13211884/maven_build.log)

**Comment by rnithinpaladin** [comment]
Hi @apoorv-byjus,

Thanks for sharing the file. We have released version 3.0.2 today, which fixes the issue you were facing.

Please follow these steps to upgrade to v3.0.2:

Check to release branch 
git pull
git checkout v3.0.2
Replace the webapp/src/config/configurations.ts file with the following file:
https://github.com/PaladinCloud/CE/blob/v3.0.2/webapp/src/config/configurations.ts
Run the following command in the installer directory:
sudo python3 manager.py install
This process will take up to 25 minutes.
Once the upgrade is complete, you should be able to install PaladinCloud without any errors.

Thanks,
Nithin

**Comment by rnithinpaladin** [comment]
Hi @apoorv-byjus 

If you are available for a call tomorrow we can sync up and resolve this issue and complete the installation.
Please let me know when your availability

Thanks,
Nithin

**Comment by apoorv-byjus** [comment]
Thanks @rnithinpaladin ,

Not sure if I am doing something wrong but the assets and compliance API's are failing. I am unable to scan new AWS accounts even though they are added as plugin. We are majorily trying this tools as a CSPM to replace another solution.

Thanks,
Apoorv

<img width="1728" alt="Screenshot 2023-11-01 at 08 15 04" src="https://github.com/PaladinCloud/CE/assets/122595426/da668ccd-bec2-49d4-8a7d-923e961fdd37">

**Comment by santhosh-challa** [comment]
Hi @apoorv-byjus

Can we get into a call to debug the issue further?

Please let us know your suitable time.

Thanks,
Santhosh

**Comment by Subbu-PaladinCloud** [comment]
Hi @apoorv-byjus, Hope you are able to see the data now. If you still are having issues, our team is available for a call. We can resolve this and also provide a quick overview so that you will be able to try out all features of the product. ( you can also watch videos on YouTube : https://youtu.be/KgG4_L0PFjg )

**Comment by Subbu-PaladinCloud** [comment]
Hi @apoorv-byjus , reaching out to see all fine for you, so we can close out this ticket ?

**Comment by Subbu-PaladinCloud** [comment]
Closing the issue with the assumption that the user is fine with the install steps provided.
