### ISSUE TITLE
[Question] ECS services fail to start due to Config container error

### ISSUE THREAD

**Issue by pvicol** [PaladinCloud/CE#1900]
# ❔ Question

Unable to start the ECS services to run PaladinCloud on 3.0.2 and 3.0.3

The installer runs and finishes without issues.

## 🔦 Context

Unable to start ECS services to run PaladinCloud. The only container running is the Web

## 💻 Code Sample

<img width="1714" alt="image" src="https://github.com/PaladinCloud/CE/assets/23704465/2ed22c4e-e549-419f-9b22-d3312d0d53f7">

<img width="1671" alt="image" src="https://github.com/PaladinCloud/CE/assets/23704465/10305cac-5255-4e5b-bba9-c07d3ac85b6f">

[paladin_poc_config.txt](https://github.com/PaladinCloud/CE/files/13465947/paladin_poc_config.txt)

**Comment by Subbu-PaladinCloud** [comment]
@pvicol , as pinged on slack, please let me know your availability at 8AM PT tomorrow ( 29th) to debug this situation.

**Comment by rnithinpaladin** [comment]
Hi @pvicol 
Did you deploy HTTPS with a custom domain?
