### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by estemendoza** [PaladinCloud/CE#307]
# ❔ Question

Is it normal that when installing Paladin Cloud, the installer creates 7 m4.large instances?

## 🔦 Context

I successfully installed Paladin Cloud, then I checked my EC2 instances and then I saw 7 new instances. Those are very expensive instances and I couldn't find any details about it in the Installation notes

**Comment by Steve-Hull** [comment]
Can you share the Instance names?  Normal operations is 2 steady state instances + transient instances during batch processing. I think those m4.large are transient to support batch scanning.  

I will make sure the installation docs get updated so everyone has a clear understanding of compute footprint.

**Comment by Steve-Hull** [comment]
Happy to help, thanks for installing.  I mis-spoke above, apologies, the 2 steady state are for testing purposes, not PaladinCloud execution.  We use Fargate for containers and Lambda so no EC2 required.  We also use Batch which dynamically creates and destroys EC2 as needed, the quantity and size depends on the number and size of the jobs which depends on the size of your cloud,  In our demo environment running PaladinCloud and some sample resources, Batch launches 4, m4.xLarge.  The instances launch/terminate on Paladin's default 6 hour interval.  Does this help?

I will update installation documents to make this more clear.  

AWS Batch = https://aws.amazon.com/batch/

**Comment by Steve-Hull** [comment]
[wiki Installation ](https://github.com/PaladinCloud/CE/wiki/Installation) has been updated to call out the dynamic allocation of EC2 while using Batch.  Thanks for pointing out this issues @estemendoza

**Comment by Steve-Hull** [comment]
- How does Paladin do the calculation for how many EC2 instances and type is going to create?  We can only recommend a count and type to the Batch service.  our recommendation is 4, m4.Large.  The service then adjusts count/type as it learns more about execution.

- are instances executed for 6 hours straight, is that the max time for being on or it depends on what they have to process?  Yes, it does depend on what is being processed which loosely translates to how many assets you have in your cloud.  That being said, this does not sound right.  Would you like to vid conf to discuss and triage?

**Comment by estemendoza** [comment]
Thanks for your reply, I think we are good for now, we will give it a try for a few days and will check how many resources are created
