### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by SecTheBit** [PaladinCloud/CE#345]
# ❔ Question

1. How many instances are going to be created while installing paladin?
2. I see paladin requires two subnets in local.py file . Why two of the subnets are required, because I am installing and deploying the paladin in the same subnet where my environment is.

**Comment by santhosh-challa** [comment]
Hi @SecTheBit ,

Can you please clarify Q1?
Q2, AWS recommends using two subnets for some of the services Paladin uses. For e.g Load Balancer.

Please let us know in case of any other concerns.

**Comment by SecTheBit** [comment]
Hi @santhosh-challa ,

In Q1 , I am asking about the total number of ec2 instances that will be created after installing paladin. In Issue #307 , It has been said that *We also use Batch which dynamically creates and destroys EC2 as needed, the quantity and size depends on the number and size of the jobs which depends on the size of your cloud, In our demo environment running PaladinCloud and some sample resources, Batch launches 4, m4.xLarge*. So , how should I know how many ec2 instances will be created?

**Comment by lakspp** [comment]
@SecTheBit 
There will be a minimum of 4 ec2 instances created. However, based on jobs running in batch the number of instances might increase. These instances will be destroyed once the jobs are empty.

**Comment by santhosh-challa** [comment]
closing this ticket, please open it in case of any further questions.
