### ISSUE TITLE
How to upgrade the nginx version from 1.14.0 to a higher version ?

### ISSUE THREAD

**Issue by rjvkumar18** [PaladinCloud/CE#352]
# ❔ Question

How to upgrade the nginx version from 1.14.0 to a higher version once Paladin app is installed?
Is there a command supported by Paladin?

## 🔦 Context
We are getting the below Vulnerability issue due to the nginx version.

"According to its Server response header, the installed version of nginx is 1.9.5 prior to
1.16.1 or 1.17.x prior to 1.17.3. It is, therefore, affected by multiple denial of service
vulnerabilities"

**Comment by lakspp** [comment]
@rjvkumar18 currently there is no command to upgrade the version. We have planned to upgrade the ngnix version in our future releases.

**Comment by rjvkumar18** [comment]
@lakspp thanks for the update.
Could you please provide us work around for this issue if you have any.
Can I change the nginx version in the dockerfile and do a fresh installation of Paladin ?

**Comment by santhosh-challa** [comment]
@rjvkumar18 Sure, you can update the docker file and try redeploy command. We have not tested this yet.
We will update the version in the coming releases.

**Comment by rjvkumar18** [comment]
Thanks @santhosh-challa.
