### ISSUE TITLE
404 Client Error: Not Found ("b'{"message":"No such image: **********.dkr.ecr.us-west-1.amazonaws.com/paladincloud-microservices:latest"}'")

### ISSUE THREAD

**Issue by rjvkumar18** [PaladinCloud/CE#361]
404 Client Error: Not Found

We are getting the below error while installing Paladin app. Could you please help on this.

1 error occurred:
        * null_resource.pacbot_app_ecr_APIDockerImageBuild: Error running command '/opt/CE-1.0.1/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py': exit status 1. Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/images/*********.dkr.ecr.us-west-1.amazonaws.com/paladincloud-microservices?force=True&noprune=False

**Comment by santhosh-challa** [comment]
Hi @rjvkumar18 ,

Can you please zip and share the install/log directory contents?
Also, can you please confirm if you are running the installer EC2 machine from the same VPC as Paladin desired to be installed?

Thanks

**Comment by rjvkumar18** [comment]
@santhosh-challa yes the installer machine is in the same VPC. We will try to provide you the logs asap.

**Comment by Subbu-PaladinCloud** [comment]
Hi @rjvkumar18 , any update from you on this.. are you still having issues ?

**Comment by Subbu-PaladinCloud** [comment]
Hi @rjvkumar18 , trying to follow up to see if you have any update here ?

**Comment by rjvkumar18** [comment]
Hi @Subbu-PaladinCloud, I tried a fresh installation of latest version of Paladin cloud, but I am getting the below errors.


Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[89]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[8]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[90]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[91]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[92]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[93]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[94]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[95]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[96]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[97]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[98]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[99]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_rule_engine_function_RuleEngineCloudWatchEventTargetsAws[9]: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_submit_function_CloudNotificationCollectorCloudWatchEventTarget: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_submit_function_DataCollectorCloudWatchEventTarget: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_submit_function_DataShipperCloudWatchEventTarget: : invalid or unknown key: event_bus_name



Error: aws_cloudwatch_event_target.lambda_submit_function_RecommendationsCollectorCloudWatchEventTarget: : invalid or unknown key: event_bus_name



Error: aws_db_instance.datastore_db_MySQLDatabase: : invalid or unknown key: db_name



Error: aws_ecr_repository.batch_ecr_RuleEngineEcrRepository: : invalid or unknown key: force_delete



Error: aws_ecr_repository.pacbot_app_ecr_APIEcrRepository: : invalid or unknown key: force_delete



Error: aws_ecr_repository.pacbot_app_ecr_UIEcrRepository: : invalid or unknown key: force_delete



Error: aws_s3_bucket_acl.s3_bucket_BucketAcl: Provider doesn't support resource: aws_s3_bucket_acl



Error: aws_s3_object.lambda_rule_engine_s3_upload_UploadLambdaRuleEngineZipFile: Provider doesn't support resource: aws_s3_object



Error: aws_s3_object.lambda_submit_s3_upload_UploadLambdaSubmitJobZipFile: Provider doesn't support resource: aws_s3_object

**Comment by Subbu-PaladinCloud** [comment]
Hi @rjvkumar18 , we can help you out with the install, can you let us know what is your availability ( timezone and date/time) , so we can get on a call with you to walk you thru the install.

**Comment by rjvkumar18** [comment]
Hi @Subbu-PaladinCloud , sorry for the delayed response. I will check and let you know.

**Comment by Subbu-PaladinCloud** [comment]
Hi Rajeev, based on our email discussion ( along with Ajit) , I assume your issues are resolved and we can close this ticket.  Thanks.
