### ISSUE TITLE
Provider does not support resource: aws_cloudwatch_event_bus

### ISSUE THREAD

**Issue by kkhamruddin-pk** [PaladinCloud/CE#414]
Failing at terraform stage.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/33874243/188339060-5e4af18d-fc13-4131-b09c-f00e43e88381.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/33874243/188339041-b8e5fb9c-085c-40eb-b48c-3d7123934151.png">

**Comment by kkhamruddin-pk** [comment]
Installing the lastest version of terraform fixed the issue.

sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
sudo yum -y install terraform

**Comment by santhosh-challa** [comment]
Hi @kkhamruddin-pk 

I think you are installing the Paladin from the master branch directly. Please confirm once.
It is recommended to install from the latest stable release. Please let us know if it is not clear from our docs, we will make it clear!

We are in the process of releasing the latest release today. We plan to update the docs as soon as we make a new release.
You can also look at our contributing docs [here](https://github.com/PaladinCloud/CE/blob/master/CONTRIBUTING.md)

Thanks for your PR. We will review your PR post our latest release today. Please share your pointers in case anything is not clear in our documentation.

Thanks,
Santhosh
