### ISSUE TITLE
Install issue, Fails Terraform step 8

### ISSUE THREAD

**Issue by SilvarisIT** [PaladinCloud/CE#431]
## Microservices
- Spring boot Applications:
 
 - Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 
 - 1.8
 
 

## Summary
The installer is failing during Step 8 of the Terraform plan.

debug.log tail shows
Error: aws_s3_object.lambda_submit_s3_upload_UploadLambdaSubmitJobZipFile: Provider doesn't support resource: aws_s3_object

error.log tail shows
Error: aws_s3_object.lambda_submit_s3_upload_UploadLambdaSubmitJobZipFile: Provider doesn't support resource: aws_s3_object

## Reproduce steps
Launch the installer

## Expected Results
Completed install

## Actual Results
Install fails

**Comment by SilvarisIT** [comment]
Reran the prerequisite script and things seem to be working now.  Not sure what happened the first time.

**Comment by Subbu-PaladinCloud** [comment]
Hi Dave, based on our discussion, you are now set with the installation. Please provide us with your feedback.

**Comment by Subbu-PaladinCloud** [comment]
Hi Dave, hoping that your install is complete . Please let us know if you have any product feedback on our gitter or slack channels.

**Comment by Subbu-PaladinCloud** [comment]
Hi Dave, can you provide any updated here whether you would need help with install or you are good with the install.. if so, please feel free to provide us with the product feedback.

**Comment by Subbu-PaladinCloud** [comment]
Hi Dave, closing this ticket at this point, please feel free to create a new issue as needed.
