### ISSUE TITLE
ec2 instance launch fails with 20GB disk space

### ISSUE THREAD

**Issue by Gervasis** [PaladinCloud/CE#478]
## Microservices
 - Asset Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 - 1.9

## Summary
 _Recommended instance type: t2.large (Minimum 8GB memory and 20GB disk space) or more.

t2.large comes with 25GB and we cannot create one with 20GB.

## Reproduce steps
Launch an ec2 instance from the paladin AMI and change the volume to 20GB

## Expected Results
Document should be updated with 25GB minimum disk space

## Actual Results
Document should be updated with 25GB minimum disk space

**Comment by Subbu-PaladinCloud** [comment]
The wiki will be updated to reflect the change.

**Comment by Subbu-PaladinCloud** [comment]
The documentation is updated to reflect this change.
