### ISSUE TITLE
Install Fails with default value for ENABLE_VULNERABILITY_FEATURE

### ISSUE THREAD

**Issue by Gervasis** [PaladinCloud/CE#479]
## Microservices
- Spring boot Applications:
 - Asset Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 - 1.9

 

## Summary
Installation fails with config value ENABLE_VULNERABILITY_FEATURE = False, which is the default one.

## Reproduce steps
Install Paladincloud without changing the value of ENABLE_VULNERABILITY_FEATURE

## Expected Results
Update the default value to ENABLE_VULNERABILITY_FEATURE = True, to pass the installation

## Actual Results
Update the default value to ENABLE_VULNERABILITY_FEATURE = True, to pass the installation

**Comment by Subbu-PaladinCloud** [comment]
This is fixed in our latest release. @rnithinpaladin , please confirm.

**Comment by rnithinpaladin** [comment]
This will be fixed in next release

**Comment by santhosh-challa** [comment]
This has been fixed and released as part of 1.4.0
