### ISSUE TITLE
Issues while redeploying

### ISSUE THREAD

**Issue by kkhamruddin-pk** [PaladinCloud/CE#491]
[ec2-user@ip-10-0-0-89 installer]$ sudo python manager.py redeploy
############################################################
          !!!!!!! WARNING !!!!!!!
############################################################
This system works with python version 3.5 or greater.
Please create virtualenv with python3 or upgrade python

[ec2-user@ip-10-0-0-89 installer]$ python --version
Python 2.7.18

**Comment by kkhamruddin-pk** [comment]
Did cp /usr/bin/python3 /usr/bin/python and the redeploy command started.

**Comment by kkhamruddin-pk** [comment]
This time with other issues

<img width="948" alt="image" src="https://user-images.githubusercontent.com/33874243/192915076-d6b2b98b-8333-4626-ab93-ea5f17845cf2.png">

**Comment by santhosh-challa** [comment]
Hi @kkhamruddin-pk 

On the python version, we need to use python3 instead of python command. Python usually refer to 2.7 version.

On the error, can you please confirm below:

Which version was last successfully installed?

What is the current version are you trying to re deploy?

Kindly zip and provide us the installer/log directory.

Thanks.

**Comment by kkhamruddin-pk** [comment]
Hi Santhosh,

I have installed the latest version 1.3.0

**Comment by kkhamruddin-pk** [comment]
Shall we connect now, if you are available? Please share the link to connect. 

@rnithinpaladin @santhosh-challa

**Comment by rnithinpaladin** [comment]
hi @kkhamruddin-pk 

Are you trying to enable https?
make ENABLE_VULNERABILITY_FEATURE = True

**Comment by kkhamruddin-pk** [comment]
@rnithinpaladin 

No, I am trying to enable HTTPs for ALB.

The error seems to me is a declaration error of terraform.

**Comment by rnithinpaladin** [comment]
@kkhamruddin-pk  make 

make ENABLE_VULNERABILITY_FEATURE = True in **local.py** file and run sudo python3 manager.py redeploy..

**Comment by kkhamruddin-pk** [comment]
I don't want this vulnerability feature enabled as of now. 

But as per your suggestion I have enabled it to get pass through with error and the redeploy was successful.
