### ISSUE TITLE
Despite the setup being complete, I cannot access the Paladin Cloud

### ISSUE THREAD

**Issue by SohamLawar** [PaladinCloud/CE#551]
# ❔ Question
Despite the setup being complete, I cannot access the Paladin Cloud

## 🔦 Context

I am exploring Paladin Cloud.

I followed the installation instructions provided in the following documentation -

https://github.com/PaladinCloud/CE/wiki/Installation

1) After installation is complete I received the following message.
## 💻 Code Sample

    ************************************************* OUTPUT ************************************************

              MySQL Host: paladincloud-data.************.us-east-1.rds.amazonaws.com:3306

                MySQL DB: pacmandata

             DB Username: paladin

             DB Password: ***********

                 ES Host: vpc-paladincloud-data-**************************.us-east-1.es.amazonaws.com

             Kibana Host: vpc-paladincloud-data-**************************.us-east-1.es.amazonaws.com/_plugin/kibana/

       Paladin Cloud URL: http://internal-paladincloud-**********.us-east-1.elb.amazonaws.com

                   Admin: [admin@paladincloud.io](mailto:admin@paladincloud.io) / PaladinAdmin!!

                    User: [user@paladincloud.io](mailto:user@paladincloud.io) / PaladinUser!!

    *********************************************************************************************************
 
 2) In the installation instructions, there is one Note below instruction 9.

> Note: Setting up SSL before the installation will save up to thirty minutes of time. Click here for the steps to set up SSL before installation.​

Hyperlink for -  **Click here** for the steps to set up SSL before installation **is missing**.

**Comment by santhosh-challa** [comment]
Hi @SohamLawar ,

From the installation banner, you have used an internal load balancer. Can you please let us know how you are connecting to UI? It is only accessible inside of VPC. 

We are updating our docs right now, we will fix the broken links.

**Comment by SohamLawar** [comment]
> Hi @SohamLawar ,
> 
> From the installation banner, you have used an internal load balancer. Can you please let us know how you are connecting to UI? It is only accessible inside of VPC.
> 
> We are updating our docs right now, we will fix the broken links.
1) 
I am connecting to UI from the browser of my local system.
How to access UI inside of VPC?
2) Okay, Thanks

**Comment by SohamLawar** [comment]
> 

How to configure installation banner to use a public load balancer?

**Comment by Subbu-PaladinCloud** [comment]
How to access UI inside of VPC?

Please setup a windows VM in that same VPC and from within a browser on that VM ,  use the Paladin URL provided at the end of the install using with the credentials provided.

**Comment by SohamLawar** [comment]
> How to access UI inside of VPC?
> 
> Please setup a windows VM in that same VPC and from within a browser on that VM , use the Paladin URL provided at the end of the install using with the credentials provided.

Hello @Subbu-PaladinCloud ,
Thanks for quick response.
Can you please provide a document/link that would be helpful for me to create a windows VM in that same VPC?
Is there any alternative?

**Comment by Subbu-PaladinCloud** [comment]
We are in the process of updating our documentation to include this information. However, for now , please follow these steps.
1) In the VPC where you have the Paladin Installed , please launch a windows instance ( Small is fine) 
2) Set up the RDP access using the keys
3) Ensure you get the password using the keys from the prev step
4) connect to the windows VM
5) open a browser ( Chrome/Edge) , and put in the URL provided at the end of the install 
6) Use the credentials provided to login

You can also use VPN to login, if that is something you want to do.

**Comment by rnithinpaladin** [comment]
hi @SohamLawar 

https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-getting-started.html

if like to setup vpn please follow above document

**Comment by SohamLawar** [comment]
> 

Hello @Subbu-PaladinCloud ,
Thanks for the response.
The steps that you instructed for launching a windows VM worked for me.

**Comment by SohamLawar** [comment]
> Hi @SohamLawar You can setup VPN to that vpc .please refer below docement. https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-getting-started.html

Hello @rnithinpaladin ,
Let me check this and get back to you.
Which of the above alternative (Windows VM  vs VPC) is more cost efficient?

**Comment by rnithinpaladin** [comment]
Hi @SohamLawar 
Spinning windows vm is easy way.

**Comment by Subbu-PaladinCloud** [comment]
Cool good to hear that you are able to access, Please let us know on how we you plan to use the product, in other words which Cloud resources are you looking to monitor, manage.. This will help us to guide better. We can get on a call to support your use case if that is required

**Comment by Subbu-PaladinCloud** [comment]
@SohamLawar , do you have any feedback for us based on your use of the product ?

**Comment by Subbu-PaladinCloud** [comment]
Based on the feedback earlier, this issue is resolved, please feel free to open a new issue if you have any additional problems.

**Comment by SohamLawar** [comment]
> @SohamLawar , do you have any feedback for us based on your use of the product ?

No, we have not used the application yet. I will definitely provide feedback once we use this application.

**Comment by SohamLawar** [comment]
> 

@Subbu-PaladinCloud ,
Okay, Thanks
