### ISSUE TITLE
[BUG]Mandatory tag & Policy Bug

### ISSUE THREAD

**Issue by sirishanarki** [PaladinCloud/CE#794]
## Microservices
- Spring boot Applications:
 
 - Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.9
 - 1.8
 - 1.7
 

## Summary

pick a mandatory tag policy - does not match our recommended mandatory tags definition

**Comment by PaladinCloudJohn** [comment]
I'm not clear on the ask here. Is this adjusting the existing policy to work with the user-defined mandatory tags feature? Or are these policies that don't work at all?

**Comment by Subbu-PaladinCloud** [comment]
Fixed
