### ISSUE TITLE
unable to redeploy 

### ISSUE THREAD

**Issue by kkhamruddin-pk** [PaladinCloud/CE#795]
Hi Team,

I am trying to add an azure account to local.py and trying to redeploy. But, unable to redeploy it. Please see the below error for reference.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/33874243/217471346-8bf18865-4657-4ccb-ab9e-c6bffd5fc739.png">

I am using v1.5.2 release. Please help

**Comment by rnithinpaladin** [comment]
Hi @kkhamruddin-pk 

What is value of ENABLE_VULNERABILITY_FEATURE in local.py ?

**Comment by kkhamruddin-pk** [comment]
Hi Nithin

It is set to true

**Comment by rnithinpaladin** [comment]
if you are not using Vulnerability feature than it can be False

**Comment by kkhamruddin-pk** [comment]
yes, I am available now

**Comment by rnithinpaladin** [comment]
To join the video meeting, click this link: meet.google.com/ruq-eezj-whr

To join by phone instead, dial (US) +1 216-930-7750 and enter this PIN: 539 534 671#

More phone numbers: https://tel.meet/ruq-eezj-whr?pin=3485134720848

**Comment by rnithinpaladin** [comment]
Please join above link

**Comment by Subbu-PaladinCloud** [comment]
fixed in the new version 3.0
