### ISSUE TITLE
Rename Creation Date to Date Created, add time stamp

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#885]
On the Policy Violations Details page, rename Creation Date to Date Created, and add the timestamp of when it was created.

**Comment by Subbu-PaladinCloud** [comment]
Hello @Preston-Dailey, would you be able to join our community slack ( clicking on the slack icon on our site https://paladincloud.io/) .. that would help us to engage with you in an expedited way.

**Comment by Preston-Dailey** [comment]
Absolutely, thank you!
