### ISSUE TITLE
Fix inconsistent Asset type naming

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#887]
inconsistent Asset type naming e.g. Securitypricings, Gkecluster, and Mysqlflexible.  
Verify all Asset Types are Singular AND use their proper Display Name.

**Comment by beingtechsavy** [comment]
I would like to work on this issue!

**Comment by PaladinCloudJohn** [comment]
Removing this from the good first issue list as the direction is unclear. We will put together a spreadsheet of all the re-names that need to happen and then re-post the issue.
