### ISSUE TITLE
rename Issue ID column to Violation ID

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#888]
The Violations List View needs to have the Issue ID column renamed to Violation ID

**Comment by MarkovianPD** [comment]
I'm new at contributing but trying to get my foot in the door with it. I've gone through all the steps but "Compare & pull request" does not appear. Hopefully I did everything correctly!

**Comment by Subbu-PaladinCloud** [comment]
Hello @MarkovianPD, would you be able to join our community slack ( clicking on the slack icon on our site https://paladincloud.io/) .. that would help us to engage with you in an expedited way.

**Comment by PaladinCloudJohn** [comment]
@MarkovianPD I see you already forked the Repo, That is the right first step. You will want to make the change from within your fork and then create a PR from there. 

I looked at the new branch [you created](https://github.com/MarkovianPD/CE-Issue-ID-rename/tree/rename-Issue-ID) but I don't see any new commits (maybe I just missed them). You will want to commit the change first and then you should be able to make a PR over to our repo. After step 3 of the [Sending a PR workflow](https://github.com/PaladinCloud/CE/blob/master/CONTRIBUTING.md#sending-a-pull-request) you add your changes and then continue with the other steps.
