### ISSUE TITLE
[BUG] Rename "Creation On" to "Date Created"

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#939]
## Summary

On the policy details page, the title "Creation On" needs renamed to "Date Created"

Screenshot: https://drive.google.com/file/d/1a6xMwMWccGLyH4jbRquU5RxegmKOEIJk/view

**Comment by Shubham-Godambe** [comment]
hey , is this still an issue? If yes can I work on this?

**Comment by PaladinCloudJohn** [comment]
Thanks for checking @Shubham-Godambe, but I believe @ujwalkumar1995's PR fixes this. I'll get out some more issues this week that might good candidates to work on.

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
