### ISSUE TITLE
[BUG] UI does not redirect to login for expired sessions

### ISSUE THREAD

**Issue by bmanuel1974** [PaladinCloud/CE#940]
## Webapp
 
- OS Type: Linux

## Summary
If you leave the UI open long enough for the session to expire, all pages in the UI continue to load, but all lists and dashboards are empty.

Looking at the browser console, all API calls are turning http status 401.

## Reproduce steps
Stay logged into the UI long enough for your session to expire.

## Expected Results
UI should redirect to login page on expired session to allow the user to login again.

## Actual Results
UI does not alert you that your session is inactive.  No errors or warnings on the page about loading data.

**Comment by PaladinCloudJohn** [comment]
Thanks for logging this issue, @bmanuel1974.  Engineering says they will have a fix for this in the 2.0.2 release due in a couple of days.

**Comment by Subbu-PaladinCloud** [comment]
Hi @bmanuel1974 , we have this bug in our backlog and have fixed it. This will be part of our 2.0.2 release.

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
