### ISSUE TITLE
[BUG] "AccountName" renamed to "Account Name"

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#941]
## Summary

On the Violations page, the filter "AccountName" should be named to "Account Name" (needs a space added)

[Screenshot](https://drive.google.com/file/d/1BRjtZ3A5jEtllkjdIApB9vX_rJPgA_ko/view)

**Comment by majormoses** [comment]
Is this what you are referring to?

https://github.com/PaladinCloud/CE/blob/a55289458e1ba6c0ab283196bff48e6808509f61/commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java#L114-L118

Is there any documentation that states when it should and should not have a space between terms?

**Comment by PaladinCloudJohn** [comment]
Yes, I believe that's the spot, and you make a great point. I lean towards it should always be with a space if it's for display purposes, but that should likely also apply to many of those other values too. Let me check with the team and get back to you.

**Comment by PaladinCloudJohn** [comment]
Anywhere that account name is displayed to users, then it should have a space. So, if this bleeds into other pages or filters, that should be good. Of course, cleaning up the codebase needs to happen at some point, but to keep this issue from scope creep, let's scope this issue to improve the Violations Page UI.

**Comment by Shubham-Godambe** [comment]
Hey can I  Solve this issue?

**Comment by Subbu-PaladinCloud** [comment]
Fixed in 3.0
