### ISSUE TITLE
[BUG] Policy view: change "Title" to "Policy"

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#969]
On the Policy page, the policies are listed under the heading of "Title" when they should be listed under "Policy".
<img width="1347" alt="Screenshot 2023-03-16 at 11 11 49 AM" src="https://user-images.githubusercontent.com/119881913/225760171-dd142f24-a4ec-4d08-829a-f6f5da20550b.png">

**Comment by Mayankjain2023** [comment]
Assign this to me

**Comment by surajdubey08** [comment]
Hi @PaladinCloudJohn,
I have gone through the documentation of PaladinCloud and understood the issue. I would like to contribute to this project. It would be great if I can be assigned to this Issue. 😀

**Comment by surajdubey08** [comment]
Fixed Issue #969

**Comment by PaladinCloudJohn** [comment]
Thanks, @surajdubey08, for submitting a PR for this request. It looks good.

**Comment by PaladinCloudJohn** [comment]
@Mayankjain2023 We usually don't assign issues for more minor changes like this that only impact a single file. If you are still interested in contributing, we'd appreciate it. Consider issue #970; it is similar but requires renaming two columns. Thanks for taking a look at our code.

**Comment by PaladinCloudJohn** [comment]
Yes, once a second person from the engineering team reviews and approves the change, it will be merged into the main branch, and the issue will be officially closed. 

We have a [community slack](https://join.slack.com/t/paladincloudcommunity/shared_invite/zt-1c2ehv1rm-KkIBLKkHZhjs543ZArbiAg) channel for contributors and weekly office hours that you are more than welcome to.

We are also trying to get the word out about the project, so If you haven't already, we appreciate it when folks give our repo a Star.
