### ISSUE TITLE
[BUG] Admin: Policy: Edit Policy: Tooltip does not display

### ISSUE THREAD

**Issue by PaladinCloudJohn** [PaladinCloud/CE#971]
## Summary
When hovering over the "i" icon indicating a tooltip, it does not display. I was told the data is in the system, but it is not displaying.
[This file](https://github.com/PaladinCloud/CE/blob/7c42ec9cecb6f99188356454421ace5d2aa1ec2a/webapp/src/app/shared/input-field/input-field.component.html) holds the code for the tooltip HTML, but this seems like an issue with js.
## Reproduce steps

Hover the cursor over the icon

## Expected Results

A popup displaying information as a tooltip

## Actual Results

Nothing happens

<img width="1155" alt="Screenshot 2023-03-16 at 10 34 15 AM" src="https://user-images.githubusercontent.com/119881913/225761396-478e17dc-3df2-44dd-b22b-ea798da89ad8.png">

**Comment by ranadheer-b** [comment]
Hi @PaladinCloudJohn , this issue is resolved. So, closing this issue.
