### ISSUE TITLE
[BUG] Login stuck with the message "Please wait, while we fetch your access roles..." while login for the first time

### ISSUE THREAD

**Issue by shoebshaikh1** [PaladinCloud/CE#980]
After successful installation of version 2.0, unable to login using the user credentials created using Cognito. The login screen is stuck with the message "Please wait, while we fetch your access roles...". 
I have followed all the exact steps mentioned in the installation document. Can someone let me know what am I missing here? Appreciate your help, thanks!

**Comment by Subbu-PaladinCloud** [comment]
@shoebshaikh1, Could you please check https://github.com/PaladinCloud/CE/wiki/Paladin-Cloud-User-Management-with-AWS-Cognito  to see if the configuration needed for Cognito is complete ? if you are still getting stuck, please post your Cognito screenshots so we can see what is going on.

**Comment by shoebshaikh1** [comment]
Hi @Subbu-PaladinCloud, thanks for your reply. I have checked the Cognito configurations in the document link provided by you and they are exactly the same. However, I am still facing the same issue. I have also tried installing the latest version but facing the same issue. I am attaching the screenshot of the message I am getting while I try to login to Paladin after the setup is completed. Thanks!
<img width="745" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/21313952/226868853-d8b9c541-71f6-45e5-be42-aad6caebf355.png">

**Comment by Subbu-PaladinCloud** [comment]
Sorry to hear you are still having an issue, let me try and get some help.

**Comment by plyubich** [comment]
@shoebshaikh1 would you be able to provide a screenshot of you Console and Network tab?

If running in Chrome:

- open a new tab and open dev tools: chrome menu -> more tools -> dev tools 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31665420/226986542-212db79e-df07-4770-a0ab-416ff418551a.png">

- In dev tools - please take a screenshots of both the "console" and "network" tabs.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/31665420/226987244-9945b1f0-e4f4-43bf-8b02-451583f80da9.png">

**Comment by jrastaban** [comment]
@shoebshaikh1 are you using a custom domain like Paladincloud.mycompany.com or the one AWS creates for you?

**Comment by shoebshaikh1** [comment]
@jrastaban - I am using the one which is created by AWS.

**Comment by jrastaban** [comment]
I ran into this issue when using the AWS domain too, even with the cert manager SSL. Are you able to get a custom domain that you can add? 

That should fix the app freezing on fetching access roles after logging in.

**Comment by shoebshaikh1** [comment]
Hi @jrastaban @Subbu-PaladinCloud, I created a private hosted zone on AWS and created a custom domain to map with the AWS load balancer endpoint. Also, I created an SSL certificate using this custom domain and imported the cert onto AWS Certificate Manager.

However, it still gives me the same error. Appreciate your time and help, thanks!

**Comment by Subbu-PaladinCloud** [comment]
@shoebshaikh1 , would you have some time to get on a call with us so we can walk through your install and see the issues ? if you are in IST Timezone , we can have one of our Tech to get in touch with you in that timezone.

**Comment by shoebshaikh1** [comment]
Hi @Subbu-PaladinCloud , yes we can get on a call and look into the issue at the earliest. Let me know when can we connect today. I am currently in the IST time zone. Thanks!

**Comment by Subbu-PaladinCloud** [comment]
@shoebshaikh1 , let me see our team availability today.

**Comment by shoebshaikh1** [comment]
@Subbu-PaladinCloud sure, let me know.

**Comment by rnithinpaladin** [comment]
Hi @shoebshaikh1
Can we connect at 6.00pm IST ?

**Comment by shoebshaikh1** [comment]
Hi @rnithinpaladin , yes we can connect at 6:00 PM IST. Let me know how can we connect.

**Comment by shoebshaikh1** [comment]
shoeb.shaikh@flentas.com

**Comment by shoebshaikh1** [comment]
@rnithinpaladin  it is - shoeb.shaikh @ flentas.com

**Comment by shoebshaikh1** [comment]
@rnithinpaladin  it is shoeb.shaikh@flentas . com

**Comment by shoebshaikh1** [comment]
@rnithinpaladin  I am unable to post my email ID here

**Comment by rnithinpaladin** [comment]
Hi @shoebshaikh1 check mail i have shared an invite

**Comment by rnithinpaladin** [comment]
Hi @shoebshaikh1 please check mail i have shared an invite

**Comment by rnithinpaladin** [comment]
Hi, As discussed I will share a meeting link, Will go over  installer process.

Please join slack channel http://paladincloudcommunity.slack.com/
Thanks,

**Comment by Subbu-PaladinCloud** [comment]
Thanks @rnithinpaladin for jumping on this. @shoebshaikh1 , please join our slack channel. It is much easier to communicate there and we could jump on a huddle much easier.

**Comment by Subbu-PaladinCloud** [comment]
@shoebshaikh1 , please let us know if you are good based on the call this morning. If you need any additional help, please reach out to @rnithinpaladin. Also it would be great if you join our slack for quicker response and further engagements.

**Comment by shoebshaikh1** [comment]
@Subbu-PaladinCloud @rnithinpaladin Thank you for your great support. For now, the issue is solved and we are able to login into Paladin dashboard. Appreciate your time and support, and yes I'll connect with you on the Slack channel. Thanks!

**Comment by shoebshaikh1** [comment]
Hi @rnithinpaladin, I was trying to add the AWS account to Paladin and I am facing some issues as I had to run the upgrade command which redeployed the entire stack probably. I made the same changes in the task definitions that we had made earlier, however, I am still getting the same error and unable to log in. Can we quickly connect and check the configurations once? Thanks!

**Comment by tejapv** [comment]
Hi @shoebshaikh1 , what is the resolution for this issue? I have the exact same issue. It would really help the community if you can provide the root cause and resolution steps.

**Comment by PaladinCloudJohn** [comment]
@tejapv There are a few causes of why this happens, but it's usually around making sure that the [SSL cert and domain are playing well with Cognito](https://github.com/PaladinCloud/CE/wiki/Deploy-Paladin). Can you open a new issue since this one is closed? We can make sure we get this resolved for you.

**Comment by tejapv** [comment]
Sure. I will open a new issue. Thank you.
