### ISSUE TITLE
[Enhancement - Dashboard] Update legend order in Violations by Severity Tile -> View Trends

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#997]
# 🙋 feature request

Legend order should be:

**Critical, High, Medium, Low, Total**

**Comment by astra1** [comment]
working on it

**Comment by plyubich** [comment]
![image](https://user-images.githubusercontent.com/31665420/227663173-3b44122a-4609-4ea1-ad82-562acae29125.jpeg)
