### ISSUE TITLE
[Enhancement - Dashboard] Replace the Custom calendar selection with a calendar control.

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#998]
# 🙋 feature request

<img width="889" alt="image" src="https://user-images.githubusercontent.com/31665420/227598497-238122bc-66bd-4aa2-8675-236ff765c95d.png">

**Comment by astra1** [comment]
i'll pickup the issue

**Comment by astra1** [comment]
@plyubich 

https://user-images.githubusercontent.com/4422785/227731781-20b23511-1778-42ee-b0a7-d2ac19ee7e88.mp4
