### ISSUE TITLE
[Enhancement - Dashboard] Update the table look and feel in Policy Compliance Overview

### ISSUE THREAD

**Issue by plyubich** [PaladinCloud/CE#999]
# 🙋 feature request

<img width="865" alt="image" src="https://user-images.githubusercontent.com/31665420/227600217-e7d8de1b-3bd2-4f61-b1f8-2acc3b571f76.png">

**Comment by astra1** [comment]
working on it

**Comment by Steve-Hull** [comment]
very nice work, can teh row fonts be smaller also?  They look too big?
